USE machine ;
CREATE TABLE TB_DEPT(
	no BIGINT AUTO_INCREMENT ,
	name VARCHAR(50) ,
	CONSTRAINT PK_DEPT_NO PRIMARY KEY(no)
); 

INSERT INTO TB_DEPT(name) VALUES ('开发部');
INSERT INTO TB_DEPT(name) VALUES ('财务部');
INSERT INTO TB_DEPT(name) VALUES ('市场部');
INSERT INTO TB_DEPT(name) VALUES ('后勤部');
INSERT INTO TB_DEPT(name) VALUES ('公关部');